config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'main/help'

  get 'main/about'

  get 'main/goodbye'

end

app/models/course.rb
class Course
  attr_accessor :instructor, :name, :number

  def initialize (instructor, name, number)
    @instructor = instructor
    @name = name
    @number = number
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    course1 = Course.new("Azadegan","Java",175)
    course2 = Course.new("Karne","OS",501)
    @courses = [course1,course2]
  end

  def help
  end

  def about
  end

  def goodbye
  end

  def time
    #the Time.now gives you the current time.

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lec2DemoRails42</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/goodbye.html.erb
<h1>Main#goodbye</h1>
<%= link_to "Back to home", main_index_path%>

app/views/main/help.html.erb
<h1>Main#help</h1>
<p>Find me in app/views/main/help.html.erb</p>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>List of courses</p>
<title> main page </title>
<ul>
  <% for course in @courses %>
      <li> <%=course.name + " " + (course.number).to_s%> </li>
  <%end%>
</ul>

<%= link_to "Goodbye", url_for("/main/goodbye")%>